import type {SimParams} from './types';
export type ControlDef={id:string;label:string;value:number;kind:'allocation'|'strategy'|'initial'|'uncertainty'};
export const controls:ControlDef[]=[
 {id:'transport',label:'打上げ・宇宙輸送',value:15,kind:'allocation'},{id:'autonomy',label:'自律運用・ロボット',value:14,kind:'allocation'},{id:'life_support',label:'生命維持・循環技術',value:11,kind:'allocation'},{id:'energy',label:'宇宙エネルギー',value:10,kind:'allocation'},{id:'domestic_supply',label:'国内供給網',value:14,kind:'allocation'},{id:'people_research',label:'人材・研究開発',value:14,kind:'allocation'},{id:'international_connection',label:'国際接続・標準化',value:11,kind:'allocation'},{id:'open_platform',label:'開放基盤',value:11,kind:'allocation'},
 {id:'domestic_procurement',label:'国内調達重視',value:60,kind:'strategy'},{id:'technology_openness',label:'技術公開度',value:55,kind:'strategy'},{id:'dependency_tolerance',label:'国際依存の許容度',value:45,kind:'strategy'},{id:'short_term_orientation',label:'短期成果の優先度',value:40,kind:'strategy'},{id:'risk_tolerance',label:'リスク許容度',value:50,kind:'strategy'},
 {id:'technology_readiness',label:'初期技術成熟度',value:58,kind:'initial'},{id:'industrial_capacity',label:'国内産業基盤',value:55,kind:'initial'},{id:'talent_base',label:'宇宙人材基盤',value:48,kind:'initial'},{id:'public_support',label:'初期国民支持',value:52,kind:'initial'},
 {id:'launch_cost_pressure',label:'打上げ費用圧力',value:50,kind:'uncertainty'},{id:'supply_disruption',label:'供給途絶リスク',value:30,kind:'uncertainty'},{id:'international_friction',label:'国際摩擦',value:35,kind:'uncertainty'}];
export const defaults:SimParams=Object.fromEntries(controls.map(c=>[c.id,c.value]));
export function normalizeAllocations(p:SimParams):SimParams{const out={...p},ids=controls.filter(c=>c.kind==='allocation').map(c=>c.id),raw=ids.map(id=>Number.isFinite(out[id])?Math.max(0,out[id]):0),sum=raw.reduce((n,v)=>n+v,0);if(sum<=0){ids.forEach((id,i)=>out[id]=i<4?13:12);return out}const quotas=raw.map(v=>v/sum*100),integers=quotas.map(Math.floor);let remaining=100-integers.reduce((n,v)=>n+v,0);const order=quotas.map((v,i)=>({i,remainder:v-integers[i]})).sort((a,b)=>b.remainder-a.remainder||a.i-b.i);for(let i=0;i<remaining;i++)integers[order[i].i]++;ids.forEach((id,i)=>out[id]=integers[i]);return out}
