import Phaser from 'phaser';import './style.css';import './responsive.css';import {controls,defaults,normalizeAllocations} from './data';import type {SimulationResult} from './types';import {ConstellationScene} from './ConstellationScene';
const app=document.querySelector<HTMLDivElement>('#app')!;let params={...defaults};
app.innerHTML=`<header><div><strong>CAUSAL CONSTELLATION</strong><h1>宇宙文明の選択肢を、同じ未来条件で比較する</h1></div><div class="mode">ローカル・マルチエージェントPDCA（4ラウンド）</div><label>シナリオ名<input value="デフォルトシナリオ" aria-label="シナリオ名"></label></header><main><aside class="panel controls"><h2>パラメータを編集</h2><div id="control-list"></div><button id="run">▶ シミュレーションを実行</button><output id="status">実行待ち</output></aside><section class="stage"><div id="game" aria-label="三領域の因果コンステレーション"></div><div class="legend">→ 因果リンク　⋯ フィードバックループ　✦ 選択された介入パス</div><section class="timeline"><h2>シミュレーションタイムライン（PDCAサイクル）</h2><div id="rounds"></div></section></section><aside class="panel evidence"><h2>エビデンス＆トレース</h2><div id="current"></div><p id="engine"></p><h3>提案と意思決定</h3><div id="proposals"></div><h3>アウトプット指標（6軸）</h3><div id="axes"></div><details><summary>因果トレースを表示</summary><ol id="trace"></ol></details></aside></main><footer>本シミュレーションは仮説的な因果関係に基づく探索的分析であり、実在の未来を保証するものではありません。<span>● ローカル実行モード</span></footer>`;
function el<K extends keyof HTMLElementTagNameMap>(tag:K,cls?:string,text?:string){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
const list=document.querySelector('#control-list')!;let activeKind='';controls.forEach((c,i)=>{if(c.kind!==activeKind){activeKind=c.kind;list.append(el('h3','control-group',({allocation:'予算配分（合計100）',strategy:'戦略',initial:'初期状態',uncertainty:'不確実性'} as const)[c.kind]))}const label=el('label','control'),head=el('span'),name=el('span','',c.label),value=el('b','',(c.value/100).toFixed(2)),input=el('input') as HTMLInputElement;value.id=`v${i}`;head.append(name,value);input.type='range';input.min='0';input.max='100';input.value=String(c.value);input.dataset.key=c.id;input.dataset.i=String(i);input.setAttribute('aria-label',c.label);label.append(head,input);list.append(label)});
list.addEventListener('input',e=>{const t=e.target as HTMLInputElement;if(t.type==='range'){params[t.dataset.key!]=+t.value;document.querySelector(`#v${t.dataset.i}`)!.textContent=(+t.value/100).toFixed(2)}});function clear(q:string){const n=document.querySelector(q)!;n.replaceChildren();return n}
function render(r:SimulationResult){const current=clear('#current'),box=el('div','current');box.append(el('span','','現在のラウンド'));const strong=el('strong','',String(r.year));strong.append(el('small','',`（ラウンド ${r.round}）`));box.append(strong,el('span','',`経過ターン ${r.round*6} / 24`));current.append(box);document.querySelector('#engine')!.textContent=`意思決定エンジン: ${r.decision_engine}`;const proposals=clear('#proposals');r.proposals.forEach(p=>{const row=el('div',`proposal ${p.accepted?'yes':'no'}`),title=el('span','',`${p.accepted?'✓':'×'} ${p.title}`),score=el('b','',`${p.score>0?'+':''}${p.score}`);title.title=`提案主体: ${p.agent}`;row.append(title,score);proposals.append(row)});const axes=clear('#axes');r.axes.forEach(a=>{const row=el('div','axis'),bar=el('i');bar.style.setProperty('--c',/^#[0-9a-f]{6}$/i.test(a.color)?a.color:'#31aaff');bar.style.setProperty('--v',`${Math.max(0,Math.min(100,a.value))}%`);row.append(el('span','',a.label),bar,el('b','',(a.value/100).toFixed(2)));axes.append(row)});const trace=clear('#trace');r.trace.forEach(x=>trace.append(el('li','',x)));const rounds=clear('#rounds');[2026,2030,2035,2040].forEach((y,i)=>{const b=el('button',`round ${i+1===r.round?'active':''}`) as HTMLButtonElement;b.dataset.round=String(i+1);b.append(el('b','',String(y)),el('span','',['計画 (Plan)','実行 (Do)','評価 (Check)','改善 (Act)'][i]));rounds.append(b)})}
async function runSimulation(){const s=document.querySelector('#status')!;s.textContent='5主体が4ラウンド協議中…';params=normalizeAllocations(params);try{const res=await fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parameters:params,rounds:4})});if(!res.ok)throw new Error(String(res.status));render(await res.json() as SimulationResult);s.textContent='ローカル決定論シミュレーション完了'}catch(error){s.textContent=`実行失敗: ${error instanceof Error?error.message:'unknown'}`}}
document.querySelector('#run')!.addEventListener('click',runSimulation);void runSimulation();
new Phaser.Game({type:Phaser.AUTO,parent:'game',transparent:true,scene:[ConstellationScene],scale:{mode:Phaser.Scale.RESIZE,width:'100%',height:'100%'},render:{antialias:true}});
